language: node_js
node_js:
- '5'
services:
- mongodb
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  on:
    tags: true
    branches: true
    repo: octoblu/meshblu-core-task-search-device
  api_key:
    secure: BP4JPTnFPah4FfdxXvzRI7v+rulAV9XMhRG/Ztzsh9qRFVa3Cb4dAtpbW5MM3Uq0GkRnSBZzDCdQMtus0gKIYPyFEaVyc/2YOVI9OvKvkgkn/pZ0/hV+nL+jipH3ZFrrZcdfIWKpIYYl/Ai1vrJkUSgtw5DnsJGqYpgX+DWYaRm2iVptuwvIZZ2hA5/TOwO3uN0gnRg4Cf7PyfmrQQ5IXNIqndzI2VU7E9JTku6lezj+CD47FcpojNjQguv++9MXd3FeZXnxuXfWVNR4sz8D3/kYDLJTCDp7M9CWvr6PJtK9YRFv5TEZEHTWKoL5I9EDn/R7GQmjExGA8ZXcPasF28CYNFD3Faa5nY7PhMJbkHGWuCVAPx2/tLqJzohDKcKNrH7ujTePHxwAI2I4QOy2wIO5iZM6Qe/vJhg+TqOwaU7KPjmg6XsNd5Kb90Hhodzz8A0X1ZGxh2PqPjSNAKdmRmi/9oNT68gtyZL7kzmkjPv5/h3MeM6qzSmSlkQtgGYNntVIN0aRH3qTT0q1CZ0alnWb+TqDbjAKKRyDOi1RgqMc7+iZWRzyRLGX/lsh5chszkye0eCEIi+pLvU63dXhNnaX1Nw0XLr2beFOWgNWB8nATCgTsdbGjA5w5LuiuxCF7VGrkKRGKP04y5KwklLkTAp8k9IPFzPPbXbQodLGaxw=
