language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
services:
- mongodb
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: BdgyvciB1vvbjnV1ny3WOvP5nzwhy2Zjmy0bZ8kXEmsQ0jLUCtnpAdlPSm1myuA2NpvhMRaU4zZtiNTKy7BDOrI3KPv4KUr6DYVKuSTOsMG2t40nZg85WRINfNukn5Teioz+4qfyN5B4ix37AWsw/6nywByGOzEXoij9BKK+n8or/fImmVAMPfNXRzRtem+x5Zaqqlx0YpnVlkYnN5Vae3/Ndd/UTh4fyFOIDJOHRzVeAAHrxW46v5kmaFLlrSPTsVRE88trDG7NF9U+zH4nzBBKBkS+rDsSeMLJFfqihMEeB6U+XxgV2D7Ji5zToaXWk9lHf2uMQoDRmet54fgStVXvgJ1bauoiFFD5Op5i8sjpuzNYavSjjZSfMTm2PMzJu5/YqGsfM/nBpH/ADci3leDnDD/pmi2BP/nxgP67S9nXNqu8BAjyq9w+1WbmvqpMYpJ07Zws2IM587gpFXYTBPZMhYpAygQYGCI+76gdDqt0Scf1HvOafuRlTUQrm8SvQC5/b7+/DkLSLzsYY0umuwsK5UknLzLySdXwwfk3DR9ONyMwAkfiOp3DAe57vmfynRCYqoQwuRKZXFEZJU1+hbKsXOD88HiEKQNLJoc7iILrAz6NQhd0xLw9QxPOoVARjb2wn9vpCzVMzunS9fSnMFFe5qLez8jAT+BjKvLfV3U=
  on:
    tags: true
    repo: octoblu/meshblu-core-task-search-device
