language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
services:
- mongodb
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: ntYSuss+cuImK673ao52THSV+pSmlwWyjSvkOgSVTGqDyV/qFcTBVLEffbC5R0WCxJCybYvH1APEEa8g62o5ufZB3aqOqfSmxm9NyqNNHUUCSGWAHiMtzgwKILwZzAPdTgbDoxGgpNdi6cfDo4F1bozQENMGbtSbZa6y12R1M5bPFezKrXG+TYE/2qtubp5tF863G3DB1bP/ibgfr4lJPKEBgM+WZFu2FoKPAbkuI+Qvwa8uKLg1JF74/f1nteBE9uiNi7bdWgg1oXISb9SdJJSWPGnYUFhGWRpclknvUKePCB1Oo83VumGCI9z8IFSSnVj/qPHG3pyjm7D87j4ohi3GbJxI9GhPlU3cEIX2hr/4QnbsJlq3kk5VQ6RetOL7D6HdzXw/eg5Pdi7VYX9hPkYg+w+qyoQ7VVGSG8GlPAlnbQTq7e1JvVH6XpA0TnVokcKl6EpK62/UwQcywjiKmnwi7EI/RT82a/o0MCfTuK8HPY05HbDFl85kkxFQCO79jtL4u3QuAqS7rrK3RS6MwK1B8D2Y48wePu4cWNaRWAj3oyRS0nbotzcxvQ7xDYDXLoXAGk4CY2m19JqS91ZeN/Tf+kJd2utt295d/sfaKQnyfSc+yonn9So88yOAh7jBGyWNWEs+kP9nkXFvb6t+o8EeHbso45pe0u69Qwj1Mec=
  on:
    tags: true
    repo: octoblu/meshblu-core-task-search-device
