language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: LM7Pt0CYncALTkQfGFoztgBYR+OyHH7TM2y3S9l604skDNZpqLApI25pQ4EK/FzG04mdD0xYABfxG5BA3pdXf/xSE8iaB/RRhTF6v3vMuMeCxeg3lfnGer4ajE52TdIXQiLV38aMV3Hq4TG/SJYU8yUnAGbUe1a2XKpYym2niKIuzeVC4EfbNLv8m4UKXkZju3VoBsVe6VtJdLGaazQoohvi/N10lRNQ9ZWUAFKIpOrObrYTI1YqAVCvXTgHLyZyesfO7AQbGx+hy/0SIvdm1o/Ou2MLrL2Poi0k1VdVP+ks1rQs9HM0z0ri6VCtqMLD7af2UksLCwWbelFvUWTlepHtJaVct4HwBtwNCMBE1bYmPjP7BDKS30TXnK6ZNYtHIpsyQ4XSZwqCY1k7/AjYEBZQEG4cg+CbCHp9Xtj+cJAT15fZ0u0Qpq4O417LDnC3ErgET7oV0eGm2nxcGQhTbuOXZkhQlYuJhO4P5Z3y8xX9Mmw5EoqWgz4rnyf+HtzxoVvJ5gM7+e9V/TOHIDza4045gKKJVN4Q3o5PtvBs64YyxVXYT45Sgq0+WAmwuHsU+MKMlPXSVPiysT5C+MdGlauYrhxh/YBH2xKIqvGX8Nq4/phi8HvBqncxVI4AoeFeahh5UZbgvv5qwBcykspP2ARNlOgeLZSE5GAYSIhborw=
  on:
    tags: true
    branches: true
