language: node_js
node_js:
- '5'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    code_climate:
      repo_token: "86790709d68f5a5951f01789d605f461de7bbb3e90122b453b67e3dad2bab69c"
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: WHIc8QnSVCccwxqaDtU9dqa8r+y3McYg5/wmHXILd7AYmdGY3S0as6yOa2WJaSYqOITwW0XKkOOzNzLXiT2GnBZ7drlRiWn5wy9XE6+Av1oE5ABt1VUnI9W0k+GNkdiv9x+VLfWM9v6036wH7c1y8mDBqbyfBsL+XTjaWhwBXFcn9m65fjlQ58ML0VIvV3SOiqnhzhRJtWNlkTgo54VQBJwsOQGUM4RRCKKW6eakc2SMYuXUu1tY4fRvoK8EQB8lupIbxxT57ikLFV95NOsV7fs2RLOWhqDdzl4thLQ1Gr9XuSdJn+aN5vtdnXgRIEsJq8bpQXYRZMVym/ZYYWrcGOvsZfrp80h6IAdybzmDDQerOOXgwtDSR0ELW4edvHglvVuuVGs2xSxUjB9IxCcnKW/5VGHloH9XrjgQZQawNPI170DU2aCLYZw0/QXrV+I8HRgQ/Unuuat78wq+zQOfFiiQz4khFz5r3EbGppuDTE9Pu8K2shm7+SWpmQ+gVJwyxS2t579fL6UYf89eO1dmwEZywE+sx4KRVJaAvjE9d93B1AS/IAjgqE9O+n7fGmHIU35XmVdGoNcuADICnVcngunFSuT3+2BF+87aK+Mr5I/toLmLILQEYTFu2NO2ZSAhYJSo1KVG/4e8JQbbiRpEryeVeALu84fmUGpbZt4AoMY=
  on:
    tags: true
    branches: true
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
