language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: NLmuIYjd/rj0UzRbaMuPKQLkgKCVMEacYJ2aq3yqe5I7zXk+frio6Old5K90ppMQs7p1yyKTLv6Vya8ryLsLeM0MOKBOV4j+FiaUOKREcav7krOmkp3dvNT1yOla9wQFEXww4aLLu1gsgOF+V5skpqdR8ZxUeVlkUAg9kWhZQ0GHA3KBlddEwySrfa21M5ZE2ijtgN8LKvP4xAxtM6+SOfm8Ww6F4zEDF0YpGAGLPxzAnYyaPWeJ1uf6n5kIjcRhD5swtOLi5nF9PiHCgLtSnBhXdVNb2hFonqQzSOvxbVQiDMp/D6JR8IZKvMKxEC0RWjB1SjGP2bC1ALz4acXJQ1RO4JQvGsgvZptTXXpxksL5e86fMl/3QoK57BHsZXpVHPTVSdfFSeC3mFtxgi6g/XIsqxVhujnHXt5DJGEp1fuOtmAS9M2GwxfhhxyanVmJV9RCFpMJoUe6lXy3/BUZRM2v/qwuvqafeC4lvigw3KOrtPhIjAj45cPaL2EowNuqEqgwXUa4SAHtRyqKATdexLxvPSHTGvUndj6JmxZCifAvf/pFR3+9B6iA7FAOP4zrxcQ1wH4+g1cqAj8MzPqFHUcIaLVd/yXhM4fEHRtCGeyBzyj/3fX8PZzicRRUHGTE/QaDy6Cnut9/tUhThW7L1pawxmvdGJhjG/Vb34nD95M=
  on:
    tags: true
    branches: true
